/*
 * Test data strategy for path.MyGraph.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2019-05-22 10:35 +0800.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package path.MyGraph_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import path.PackageStrategy_com_oocourse_specs2_models_Path;
/**
 * Test data strategy for path.MyGraph. Provides
 * class-scope test values for type com.oocourse.specs2.models.Path.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2019-05-22 10:35 +0800
 */
public /*@ nullable_by_default */ class ClassStrategy_com_oocourse_specs2_models_Path 
  extends PackageStrategy_com_oocourse_specs2_models_Path {
  /**
   * @return class-scope values for type com.oocourse.specs2.models.Path.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add class-scope com.oocourse.specs2.models.Path values or generators here */ });
  }

  /**
   * The use of reflection can be controlled here for  
   * parameters of type com.oocourse.specs2.models.Path
   * in this class by changing the parameters to <code>setReflective</code>
   * and <code>setMaxRecursionDepth<code>. 
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Note that lower-level strategies can override any 
   * behavior specified here by calling the same control methods in 
   * their own constructors.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public ClassStrategy_com_oocourse_specs2_models_Path() {
    super();
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
